"""
Django settings for breed_detection_backend project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
OBJECT_DETECTION_MODELS_DIR = os.path.abspath(os.path.join(BASE_DIR, 'models'))


OBJECT_DETECTION_MODEL_NAME = os.environ.get('OBJECT_DETECTION_MODEL_NAME', 'animal-breed-detector')
OBJECT_DETECTION_LABEL_MAP_FILENAME = os.environ.get('OBJECT_DETECTION_LABEL_MAP_FILENAME', 'label_map.pbtxt')
OBJECT_DETECTION_MODEL_PATH = os.path.abspath(os.path.join(OBJECT_DETECTION_MODELS_DIR, OBJECT_DETECTION_MODEL_NAME))
OBJECT_DETECTION_LABEL_MAP_PATH = os.path.abspath(os.path.join(OBJECT_DETECTION_MODEL_PATH, OBJECT_DETECTION_LABEL_MAP_FILENAME))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', "django-insecure-x*qlrye(cw_ks89s0*$vx=c@z+42j^exyu%78+!&f#wt_=vll(")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []



# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'corsheaders',
    "storages",
    "animals.apps.AnimalsConfig",
    "users.apps.UsersConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'corsheaders.middleware.CorsMiddleware',
]

ALLOWED_HOSTS=['*']
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

SESSION_COOKIE_HTTPONLY = False
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = True

ROOT_URLCONF = "breed_detection_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "breed_detection_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "mssql",
        "NAME": "kba-animal-detection-test",
        "USER": "ad-admin",
        "PASSWORD": "DBSpassword!_",
        "HOST": "kba-animal-detection-dbs.database.windows.net",
        "PORT": "1433",
        "OPTIONS": {
            "driver": os.environ.get('MSSQL_DB_DRIVER', "ODBC Driver 17 for SQL Server"),
        },
        "ATOMIC_REQUESTS": True,
    }
}

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.azure_storage.AzureStorage",
        "OPTIONS": {
            "connection_string": "DefaultEndpointsProtocol=https;AccountName=kbaanimaldetectionsta;AccountKey=8U74ETrCF8qega4xK1MXixGSd6w18CiMcUSglndd33o6/4eOMNkve+lWScc0/W4yumOscbgbG9Kr+AStj7lUKQ==;EndpointSuffix=core.windows.net",
            "account_name": "kbaanimaldetectionsta",
            "account_key": "8U74ETrCF8qega4xK1MXixGSd6w18CiMcUSglndd33o6/4eOMNkve+lWScc0/W4yumOscbgbG9Kr+AStj7lUKQ==",
            "azure_container": "uploads"
        },
    },
    "staticfiles": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": "/static",
            "base_url": "/static/"
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Kiev"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
