# Generated by Django 4.2.13 on 2024-05-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysis",
            name="original_file_path",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="result_file_path",
        ),
        migrations.AddField(
            model_name="analysis",
            name="original_file",
            field=models.FileField(default=None, upload_to=""),
        ),
        migrations.AddField(
            model_name="analysis",
            name="result_file",
            field=models.FileField(default=None, upload_to=""),
        ),
    ]
