# Generated by Django 4.2.13 on 2024-05-09 18:50

import animals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0002_remove_analysis_original_file_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="original_filename",
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="original_file",
            field=models.FileField(
                default=None, upload_to=animals.models.generate_file_name_uuid
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="result_file",
            field=models.FileField(
                default=None, upload_to=animals.models.generate_file_name_uuid
            ),
        ),
    ]
