# Generated by Django 4.2.13 on 2024-05-12 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0004_analysis_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analysis",
            options={"verbose_name_plural": "Analyses"},
        ),
        migrations.AlterModelOptions(
            name="detectedanimal",
            options={"verbose_name_plural": "Detected animals"},
        ),
    ]
